# Shebang not required. This file is sourced by other scripts.

ROOT=$(git rev-parse --show-toplevel)
DOWNLOADS="$ROOT/Downloads"

if [ -f "$ROOT/variables.sh" ] ; then
    . "$ROOT/variables.sh"
fi

set_var()
{
  local name="$1"
  local val="\"$2\""
  local file="$ROOT/variables.sh"

  [ -z "$name" ] && return
  [ -z "$val" ] && return

  if [ -f "$file" ]; then
    # Check if variable name and val already in settings
    busybox grep "^$name=$val$" "$file" > /dev/null
    if [ $? -ne 0 ]; then
      # Check is variable name exists
      busybox grep "^$name=" "$file" > /dev/null
      if [ $? -eq 0 ]; then
        # Variable name exists so just substitute value
        sed -i "s|^$name=.*|$name=$val|" "$file"
      else
        # Variable doesn't exist so append
        echo "$name=$val" >> "$file"
      fi
    fi
  else
    # Settings file doesn't exist so create it and append
    echo "# This file is automatically generated. Do not edit." > "$file"
    echo "" >> "$file"
    echo "$name=$val" > "$file"
  fi
}

msg() {
    printf "%s\n" "$*" >&2
}
